# Generated by Django 6.0 on 2025-12-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="social_media.post",
            ),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
