# Generated by Django 6.0 on 2025-12-15 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social_media", "0003_remove_post_liked_by_remove_post_shared_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("author", "content_type", "object_id")},
        ),
    ]
