# Generated by Django 6.0 on 2025-12-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0004_rename_user_reaction_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="hashtag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
