# Generated by Django 6.0 on 2025-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
